# ==============================================================================
# SERVIDOR DEDICADO DE 7 DAYS TO DIE (LinuxGSM Edition)
# Versión: 2026.1 | Imagen: vinanrra/7dtd-server
# ==============================================================================
#
# 1. PREPARACIÓN DE DIRECTORIOS (Vía Terminal en NAS):
#    Ejecuta estos comandos para asegurar que LinuxGSM pueda escribir:
#    sudo mkdir -p /mnt/APPs/7DTD-server/{saves,config,serverfiles,logs,backups}
#    sudo chown -R 1000:1000 /mnt/APPs/7DTD-server
#    sudo chmod -R 775 /mnt/APPs/7DTD-server
#
# 2. PUERTOS REQUERIDOS (Port Forwarding):
#    - 26900 (TCP/UDP): Puerto principal de comunicación.
#    - 26901-26902 (UDP): Puertos de consulta (Steam Query).
#    - 8080-8082 (TCP): Web Dashboard / Telnet (opcional para administración).
#
# 3. GESTIÓN DE MODS Y ACTUALIZACIONES:
#    - ALLOC_FIXES: Activa mejoras de rendimiento y comandos extra.
#    - BACKUP: Si se activa, realiza copias automáticas a la hora definida.
#    - START_MODE: Define qué hará el servidor al iniciar (3 = Instalar/Update y Start).
#
# 4. CONFIGURACIÓN DEL JUEGO:
#    El archivo principal de ajustes (nombre del mundo, loot, etc.) se encuentra
#    tras el primer arranque en: /mnt/APPs/7DTD-server/config/sdtdserver.cfg
# ==============================================================================



services:
  7dtdserver:
    container_name: 7dtdserver
    environment:
      - LINUXGSM_VERSION=v24.3.4
      - START_MODE=3
      - VERSION=stable
      - PUID=1000
      - PGID=1000
      - TimeZone=Europe/Madrid
      - TEST_ALERT=NO
      - UPDATE_MODS=NO
      - MODS_URLS=""
      - ALLOC_FIXES=NO
      - ALLOC_FIXES_UPDATE=NO
      - UNDEAD_LEGACY=NO
      - UNDEAD_LEGACY_VERSION=stable
      - UNDEAD_LEGACY_UPDATE=NO
      - DARKNESS_FALLS=NO
      - DARKNESS_FALLS_UPDATE=NO
      - DARKNESS_FALLS_URL=False
      - CPM=NO
      - CPM_UPDATE=NO
      - BEPINEX=NO
      - BEPINEX_UPDATE=NO
      - BACKUP=NO
      - BACKUP_HOUR=5
      - BACKUP_MAX=7
      - MONITOR=NO
    image: vinanrra/7dtd-server
    ports:
      - 26900:26900/tcp
      - 26900:26900/udp
      - 26901:26901/udp
      - 26902:26902/udp
      - 8080:8080/tcp
      - 8081:8081/tcp
      - 8082:8082/tcp
    restart: unless-stopped
    ulimits:
      nofile:
        hard: '10240'
        soft: '10240'
    volumes:
      - /mnt/APPs/7DTD-server/saves:/home/sdtdserver/.local/share/7DaysToDie/
      - >-
        /mnt/APPs/7DTD-server/config:/home/sdtdserver/lgsm/config-lgsm/sdtdserver
      - /mnt/APPs/7DTD-server/serverfiles:/home/sdtdserver/serverfiles/
      - /mnt/APPs/7DTD-server/logs:/home/sdtdserver/log/
      - /mnt/APPs/7DTD-server/backups:/home/sdtdserver/lgsm/backup/

