name: <your project name>
services:
  minidlna:
    environment:
      - MINIDLNA_MEDIA_DIR=/media
      - MINIDLNA_FRIENDLY_NAME=MyDLNA
    image: vladgh/minidlna
    network_mode: host
    restart: always
    volumes:
      - /mnt/videos:/media

